### PR TITLE
I wrote a requirement file for pip.

### PR DESCRIPTION
**Pull request by changukshin**
It may make easier to install this project.
And another thing I find is in 'train.py:72~73', If `save` directory does not exists, make it.

### CODE REVIEW

**Comment by stegben** [comment]
maybe try [`Pipenv`](https://github.com/kennethreitz/pipenv) ?

**Comment by persiyanov** [comment]
@papower1 Hi! The project also uses `numpy`. Could you add it to `requirements.txt`?

**Comment by changukshin** [comment]
@persiyanov 
It is not essential. because tensorflow1.0.1 requires numpy>=1.11.0. Still, Do you want to?
@stegben 
Maybe. But there are many others that does not know that project. `requirements.txt` is more farmiliar and popular way then that. But, Appreciate your comment. I'll remember that.

**Comment by changukshin** [comment]
Sorry, This project is not fit to tensorflow 1.0
I'll notice after recheck compatibility with tensorflow v0.12.

**Comment by changukshin** [comment]
Version 0.12. is good to go.

**Comment by persiyanov** [comment]
@papower1 Thanks!

**Pull request merged**
